version: '3'
services:
 mongodb:
   image: mongo:3.3   
   expose:                 
     - "27017"
   volumes:
     - db_data:/data/db
   environment:    
    MONGODB_DATABASE: rsvpdata
   networks:
    - rsvpnet

 web:
   image: teamcloudyuga/rsvpapp:mooc
   ports:
    - "5000:5000"
   environment:
    MONGODB_HOST: mongodb
    LINK: http://github.com/collabnix/dockerlabs
    TEXT1: DockerLabs 
    TEXT2: Garage RSVP!
    LOGO: https://logos-download.com/wp-content/uploads/2016/09/Docker_logo.png
    COMPANY: Collabnix
   networks:
    - rsvpnet

networks:
  rsvpnet:

volumes:
   db_data:
